// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJcSYc3VzH8VL8afJN5aFc91OI-iwBcE',
    appId: '1:579332573183:web:5cab27ad90dc5f502009ca',
    messagingSenderId: '579332573183',
    projectId: 'mediminder-524e8',
    authDomain: 'mediminder-524e8.firebaseapp.com',
    storageBucket: 'mediminder-524e8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYWMJ_-bQBpvfbVmoO1FiurNWe6RYP_M',
    appId: '1:579332573183:android:e45cd4ab7ae47fdc2009ca',
    messagingSenderId: '579332573183',
    projectId: 'mediminder-524e8',
    storageBucket: 'mediminder-524e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2F1a4QzeRzWMCbM7gKmsAV07YMKatT-s',
    appId: '1:579332573183:ios:cf7f72a55b4b5a402009ca',
    messagingSenderId: '579332573183',
    projectId: 'mediminder-524e8',
    storageBucket: 'mediminder-524e8.appspot.com',
    iosBundleId: 'com.example.firebaseAuthV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2F1a4QzeRzWMCbM7gKmsAV07YMKatT-s',
    appId: '1:579332573183:ios:cf7f72a55b4b5a402009ca',
    messagingSenderId: '579332573183',
    projectId: 'mediminder-524e8',
    storageBucket: 'mediminder-524e8.appspot.com',
    iosBundleId: 'com.example.firebaseAuthV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJcSYc3VzH8VL8afJN5aFc91OI-iwBcE',
    appId: '1:579332573183:web:a4076c411afa6d3d2009ca',
    messagingSenderId: '579332573183',
    projectId: 'mediminder-524e8',
    authDomain: 'mediminder-524e8.firebaseapp.com',
    storageBucket: 'mediminder-524e8.appspot.com',
  );

}